import Navbar from '@/components/Navbar/Navbar';
import Footer from '@/components/Footer/Footer';

import './globals.css';
// import type { Metadata } from 'next';
import { Inter, Sora } from 'next/font/google';

// fonts
const sora = Sora({
  subsets: ['latin'],
  variable: '--font-header',
  display: 'swap',
});

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-body',
  display: 'swap',
});

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' className='scroll-smooth'>
      <body className={`${inter.variable} ${sora.variable}`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
