import Head from 'next/head';
import Image from 'next/image';
import styled from 'styled-components';

export default function Home() {
  return (
    <PageWrapper>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main></main>

      <footer>
        <p>©Copyrights Migacz Borthers | All Rights Reserved</p>
      </footer>
    </PageWrapper>
  );
}

const PageWrapper = styled.div`
  display: inline-block;
  height: 100%;
  width: 100%;
  background-color: #1d1b3d;
  color: #f4f4f4;
`;
